// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://behobepwtvtoflaupmri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlaG9iZXB3dHZ0b2ZsYXVwbXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMjU5NzgsImV4cCI6MjA1NTYwMTk3OH0.Qu7b5QK9ksKArQ3VbvrI1fHRvOMDK89AUROp0fi-oKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);